# ===== 应用 =====
spring.application.name=backend

# ===== 服务器 =====
server.port=8080

# ===== 数据库连接 =====
spring.datasource.url=jdbc:mysql://localhost:3306/snack?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===== MyBatis =====
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.snack.backend.domain
mybatis.configuration.map-underscore-to-camel-case=true

# ===== 日志 =====
logging.level.com.snack.backend=debug